spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/oauth2-db?serverTimezone=GMT%2B8&useSSL=false&useUnicode=true&characterEncoding=utf-8&allowPublicKeyRetrieval=true&useAffectedRows=true
    username: root
    password: Jiang.252681 #
    driver-class-name: com.mysql.cj.jdbc.Driver